================================================================
							REQUISITOS
================================================================

R01- CRUD CATEGORIA
R02- CRUD TAGS
R03- CRUD CONTEÚDO (BOA PRÁTICA)
R04- EXPLORAR PRÁTICAS CADASTRADAS
R05- PESQUISAR PRÁTICA POR CATEGORIA
R06- PESQUISAR PRÁTICA POR TAGS
R07- PESQUISAR PRÁTICA POR PALAVRA-CHAVE
R08- CRUD ARQUIVO A PRÁTICA
R09- VISUALIZAR ARQUIVO DA PRÁTICA
R10- DOWNLOAD DA PRÁTICA
R11- LOGIN DO ADMINISTRADOR
----------------------------------------------------------------
R12- PÁGINA SOBRE
R13- PÁGINA DE CONTATO